### PR TITLE
Week 2 assignment

### PR DESCRIPTION
**Pull request by fghaddar**

### CODE REVIEW

**Comment by abundyMB** [comment]
It looks like everything is in order as far as I can tell. Most of the changes look to take place in the Junit test, and not in the controllers or DTOs. I'm assuming this is because you're working on things beyond Week 2, so it's hard for me to know for certain if there are any issues.

**Review by abundyMB — APPROVED** [review]
It looks like everything is in order as far as I can tell. Most of the changes look to take place in the Junit test, and not in the controllers or DTOs. I'm assuming this is because you're working on things beyond Week 2, so it's hard for me to know for certain if there are any issues.

**Comment by fghaddar** [comment]
Hey Andrew thanks for letting me know. I actually forgot to push changes to the controllers and the DTO, so I got that resolved

**Comment by hollyollyoxxenfree** [comment]
Hello Fadl,

I spent about 20 minutes reviewing these code changes. 
Your JUnit test looks good and is well documented.

**Pull request merged**
